app/projects/__init__.py
from flask import Blueprint

projects = Blueprint('projects', __name__)

from . import views

app/projects/views.py
from flask import abort, flash, g, redirect, render_template, url_for

from app import db
from app.forms import ProjectForm
from app.models import Project, ProjectState, Permission
from flask_login import login_required, current_user
from app.projects import projects
from app.security import permissions_required


@projects.route("/")
def projects_page():
    return render_template('projects.html', projects=Project.query.all())


@projects.route("/<int:pid>")
def project(pid):

    pr = Project.query.filter_by(id=pid).first()

    if not pr:
        abort(404)

    return render_template('project_ind.html', project=pr)


@projects.route("/new", methods=['GET', 'POST'])
@login_required
@permissions_required(Permission.CREATE_PROJECT)
def new_project():

    project_form = ProjectForm()

    if project_form.validate_on_submit():

        try:
            mode = ProjectState(project_form.status.data)
        except ValueError:
            abort(400)

        if project_form.pic_url:
            pic_url = project_form.pic_url
        elif project_form.pic_upload:
            raise NotImplementedError()

        project = Project(
            uid=current_user.id,
            picture=pic_url,
            title=project_form.name.data,
            body=project_form.body.data,
            start_date=project_form.start_date.data,
            status=mode.value,
            finish_date=project_form.finish_date.data if mode == ProjectState.Finished else None
        )

        db.session.add(project)
        db.session.commit()

        return redirect(url_for('.project', pid=project.id))

    else:
        for fieldName, errorMessages in project_form.errors.items():
            for err in errorMessages:
                flash("Error for {}: {}".format(fieldName, err), 'error')

        return render_template('project_new.html', form=project_form)


@projects.before_app_request
def injectEnum():

    g.project_states = {s.value: s.name for s in ProjectState}

app/templates/401.html
{% extends "base.html" %}
{% block title %} Osetr - 401 {% endblock %}

{% block content %}

{{ super() }}

<br><br>

<div class="text-center">
    <h1>Error 0x191 - Authorization required</h1>
    <img src="/static/img/kazoo.jpg" class="errorImg">
    <h2>Wait a minute, who are you?</h2>
</div>

{% endblock %}

app/templates/501.html
{% extends "base.html" %}
{% block title %} Osetr - 501 {% endblock %}

{% block content %}

{{ super() }}

<br><br>

<div class="text-center">
    <h1>Error 0x1F5 - Not Implemented</h1>
    <h2>This part of website is still being worked on</h2>
    <img src="/static/img/finch.jpg" class="errorImg">
</div>

{% endblock %}

app/templates/_macros.html
{% macro alert(tag, class, text) %} 

  {% if text != "" %}
    {% set prefix = text + " " %}
  {% else %}
    {% set prefix = "" %}
  {% endif %}

  {% with messages = get_flashed_messages(category_filter=[tag]) %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {{ class }}">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ (prefix + message) | safe }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

{% endmacro %}

{% macro render_field(field) %}
  <dt>{{ field.label }}</dt>
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

app/templates/about.html
{% extends "base.html" %}
{% set active_page = "about" %}

{% set contacts = [
    {
        'name': 'Telegram',
        'url': 'https://t.me/peterder72',
        'alias': '@peterder72',
        'icon': 'img/social/tg_small.png'
    },
    {
        'name': 'E-Mail',
        'url': 'mailto:peterder72@osetr.su',
        'alias': 'peterder72@osetr.su',
        'icon': 'img/social/mail_small.png'
    },
    {
        'name': "IRC",
        "alias": "peterder72@freenode",
        'icon': 'img/social/irc_small.png'
    },
    {
        'name': 'LinkedIn',
        'icon': 'img/social/linkedin_small.png'

    },
    {
        'name': "Keybase",
        'alias': 'peterder72',
        'url': 'https://keybase.io/peterder72',
        'icon': 'img/social/keybase_small.png'
    }
] -%}

{% block content %}

{{ super() }}

<div class="jumbotron minitron text-center">
    <h1>About me</h1>
</div>
<div id="info-container">
    <div class="row">
        <div class="col">
            <p>
                My name is Peter and I am an ICT student. I love doing software and
                hardware projects in my spare time and for my studies.
            </p>
            <p>
                This website is also one of my projects:
                it was entirely built in <i>Flask</i>.
                Source for this project is on <a href="https://gitlab.com/peteder72/homepage">GitLab</a>.
            </p>
            <p>
                If you want to contact me, you can reach me through these channels:
                {% for contact in contacts: %}
                    <div class="row">
                        <div class="col social-box">
                            <img src="{{ url_for('static', filename=contact['icon']) }}">
                        </div>
                        <div class="col">
                            {% if contact.get('url') and not contact.get('alias') %}
                                <a href="{{ contact['url'] }}">{{ contact['name'] }}</a>
                            {% else %}
                                {{ contact['name'] }}
                            {% endif %}

                            {% if contact.get('alias') %}
                            {% if contact['url'] %} 
                            (<a href="{{ contact['url'] }}">{{ contact['alias'] }}</a>)
                            {% else %}
                            ({{ contact['alias'] }})
                            {% endif %}
                            {% endif %}
                            
                        </div>
                    </div>
                    {% endfor %}
                </p>
                <p>
                    Also, if you need to send me something private, you send me an E-Mail and encrypt it with my 
                    <b>PGP key</b>, which you can get from Keybase or from <a href='/static/key.asc'>here</a>.
                </p>
        </div>
                <div class="col">
                    <div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="peter-deriabin-77b7251a4">
                        <a class="LI-simple-link" href='https://nl.linkedin.com/in/peterder72?trk=profile-badge'>
                            Peter Deriabin
                        </a>
                    </div>
                    <p>
                        Tech and languages I use the most:
                        <ul>
                            <li>Linux</li>
                            <li>Docker</li>
                            <li>Bash</li>
                            <li>Python</li>
                            <li>C{,++,#}</li>
                        </ul>
                    </p>
                </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %} 
{% import "bootstrap/wtf.html" as wtf %} 
{% import "_macros.html" as macros %}

{% set nav_bar = [
    ('main.index', 'index', 'Home', False),
    ('projects.projects_page', 'projects', 'Projects', False),
    ('main.about_page', 'about', 'About', False),
    ('main.manage', 'manage', 'Manage', True)
] -%}

{% block title %}
Osetr {% if active_page %}- {{ active_page }}{% endif %}
{% endblock %} 

{% block styles %}
<link href="//bootswatch.com/4/darkly/bootstrap.min.css" rel="stylesheet">
<link href="/static/style.css" rel="stylesheet">
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
    {% if config['TESTING'] %}
    Osetr <b><i>Testing</i></b>
    {% elif config['DEBUG'] %}
    Osetr <b><i>Debug</i></b>
    {% else %}
    Osetr
    {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            {% for path, act_name, disp_name, admin_only in nav_bar %}
                {% if not (admin_only and not current_user.admin()) %}
                <li class="nav-item {% if act_name == active_page %}active{% endif %}">
                    <a class="nav-link" href="{{ url_for(path) }}">{{ disp_name }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- To do: remove from production
      
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.rickroll') }}">Admin interface</a>
      </li>
    
      -->
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if not current_user.is_logged_in() %}
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" href="#" data-target="#modalSignupForm"><b>Sign up</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" href="#" data-target="#modalLoginForm"><b>Sign in</b></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/profile/{{ current_user.username }}"><b>{{ current_user.name }} {{ current_user.surname }}</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.signout') }}"><b>Sign out</b></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-hidden="true" style="display:none;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
            </div>
            <div class="modal-body">
                {{ macros.alert("error-login", "alert-danger", "<strong>Oh snap!</strong>") }} {{ wtf.quick_form(g.login_form) }}
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalSignupForm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Sign up</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
            </div>
            <div class="modal-body">
                {{ macros.alert('error-signup', "alert-danger", "<strong>Oh snap!</strong>") }} {{ wtf.quick_form(g.signup_form) }}
            </div>
        </div>
    </div>
</div>

{{ macros.alert('success', 'alert-success', '<strong>Yay!</strong>') }} {{ macros.alert('error', 'alert-danger', '<strong>Oh no!</strong>') }} 
{% endblock %} 
{% block scripts %}
<footer class="page-footer font-small fixed-bottom">
    <div id="copyright">
        Homepage v.{{ config['version'] }} ©peterder72, {{ now.year }}. <a href='{{ url_for("main.copyright") }}'>Used resources</a>
    </div>
{% block footer %} 
{% endblock %}
</footer>
{{ super() }}
<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
<script>
    if (window.location.hash) {
        $(document).ready(function() {
            $(window.location.hash).modal("show");
        });
    }
</script>
{% endblock %}

app/templates/confirmed.html
{% extends "base.html" %}

{% block title %} Flask - success {% endblock %}

{% block content %}
{{ super() }}
<table width="60%" style="text-align: center; margin-left: auto; margin-right: auto; margin-top: 20px">
    <tr>
        <td>
            <h1>Congratulations!</h1>
            <h2>You've confirmed your email</h2>
        </td>
    </tr>
    <tr>
        <td>
            <p>
                You can now login and feel the full power of the website, {{ user.name }}!
            </p>
        </td>
    </tr>
</table>
{% endblock %}

app/templates/copyright.html
{% extends "base.html" %}

{% block title %}
Flask - Copyright
{% endblock %}

{% block content %}

{{ super() }}


<div id="info-container">
    <h1>
        Copyright
    </h1>
    <p>
        In some places on this website
        I used copyrighted images, which require
        mentions on the website. As I don't have any other
        place for it, I'll just put it all here.
    </p>
    <ul>
        <li>
            Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> 
            from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
        </li>
    </ul>
</div>
{% endblock %}

app/templates/email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Osetr confirmation</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
            p,h1 {
                color: white;
                font-family: "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            }
            tr {
                background-color: #303030;
                text-align: center;
            }
            a {
                color: cornflowerblue;
            }
        </style>
    </head>
    <body>
        <table cellspacing="0" cellpadding="0" style="margin-left: auto; margin-right: auto; border: 0;" width=600px>
            <tr style="background-color: #444;">
                <td style="padding: 40px 0 30px 0;">
                    <p style="font-size: 40px;">
                        Osetr
                    </p>
                </td>
            </tr>
            <tr>
                <td style="padding: 20px 0 30px 0;">
                    <p style="font-size: 25px;">
                        <b>It's nice you joined</b>
                    </p>
                </td>
            </tr>
            <tr style="padding: 40px 0 30px 0;">
                <td>
                    <p style="margin-left: 20px; margin-right: 20px;">
                        Thank you for signing up on my website!
                        I'm really glad you are interested in my projects.
                        I hope you will enjoy your time on the website!
                        Stay creative!<br><br>
                        Sincerely,<br>
                        <b>peterder72</b>
                    </p>
                </td>
            </tr>
            <tr>
                <td style="padding: 10px 0 50px 0;">
                    <p>
                        P.S. Oh, and about that confirmation thing.
                        Click <a href="{{ root }}/confirm/{{ token }}">this</a> link to confirm your email 
                    </p>
                </td>
            </tr>
            <tr>
                <td style="background-color: #444;">
                    <p>
                        ©peterder72, 2019
                    </p>
                </td>
            </tr>
        </table>
    </body>
</html>

app/templates/index.html
{%- extends "base.html" -%}
{% set active_page = "index" %}

{%- block content -%}

{{ super() }}

<div class="jumbotron text-center">
        <div class="beautiful-background"></div>
        <div class="jumbotron-container">
                <h1>Osetr</h1>
                <p>peterder72's humble place</p> 
        </div>
      </div>

<div class="text-center">
        <p>
                Welcome to my website! This index page is empty for now, but you can already check
                out my <b>projects</b> and <b>about info</b>!
        </p>
        <p>
                This website is still in development. 
                If broken - contact <a href="mailto:webmaster@osetr.su">webmaster@osetr.su</a>
        </p>
</div>
{%- endblock -%}

app/templates/manage.html
{% extends "base.html" %} 
{% set active_page = "manage" %}

{% block content %} 

{{ super() }}

<div class="jumbotron minitron text-center">
    <h1>Admin console</h1>
</div>

<div id="info-container">
    <ul>
        {% for user in users %}
        <li>
            {{ user.email }}
        </li>
        {% endfor %}
    </ul>

</div>


{% endblock %}

app/templates/project_ind.html
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}

{{ super() }}

<div class="jumbotron minitron text-center">
    <h1>{{ project.title }}</h1>
</div>

<div id="info-container">
    <div class="project-container container">
        <div class="row">
          <div class="col text-left align-bottom project-date">
            <span>Status: {{ g.project_states[project.status] }}</span>
          </div>
          <div class="col text-right align-bottom project-date">
            {% if project.start_date %}
            <span>Started: {{ project.start_date }}</span>
            {% endif %} 
            {% if project.finish_date %}
            <span>Finished: {{ project.finish_date }}</span>
            {% endif %}
          </div>
        </div>
        <hr class="project-divider" />
        <div class="row">
          <div class="col project-text">
            <img
              class="project-pic"
            {% if not project.picture %}
              src="{{url_for('static', filename='img/wisdom.jpg')}}"
            {% else %}
              src="{{ project.picture }}"
            {% endif %}
            />
            {{ project.body|markdown }}
          </div>
        </div>
      </div>
</div>


{% endblock %}

app/templates/project_new.html
{% import "_macros.html" as macros %}

{% extends "base.html" %}
{% set active_page = "projects" %}

{% block head %}

{{ super() }}

{{ pagedown.include_pagedown() }}

{% endblock %}

{% block content %}

{{ super() }}

<div class="jumbotron minitron text-center">
    <h1>New project</h1>
</div>

<div id="info-container">
    <form method="POST" class="form-group">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col">
                {{ macros.render_field(form.name, class="form-control-lg") }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ macros.render_field(form.start_date, class="form-control") }}
            </div>
            <div class="col">
                {{ macros.render_field(form.pic_upload, class="form-control") }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ macros.render_field(form.finish_date, class="form-control") }}
            </div>
            <div class="col">
                OR
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ macros.render_field(form.status, class="form-control") }}
            </div>
            <div class="col">
                {{ macros.render_field(form.pic_url, class="form-control") }}

            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.body.label }}: <br> {{ form.body(rows=10) }} <br>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.submit(class="form-control") }}
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/projects.html
{% extends "base.html" %} 
{% set active_page = "projects" %}

{% block content %} 

{{ super() }}

<div class="jumbotron minitron text-center">
  <h1>Projects</h1>
</div>

<div id="info-container">
  {% if current_user.has_permission(permission.CREATE_PROJECT) %}
  <a href="{{url_for('projects.new_project')}}">
    Add new project
  </a>
  {% endif %}
  <hr class="project-divider" />
  {% for project in projects %}
  <div class="project-container container">
    <div class="row">
      <div class="col text-left align-bottom project-date">
        <span>Status: {{ g.project_states[project.status] }}</span>
      </div>
      <div class="col text-right align-bottom project-date">
        {% if project.start_date %}
        <span>Started: {{ project.start_date }}</span>
        {% endif %} 
        {% if project.finish_date %}
        <span>Finished: {{ project.finish_date }}</span>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col">
        <span class="project-name">{{ project.title }}</span>
      </div>
    </div>
    <div class="row project-body">
      <div class="col">
        <img
          class="project-pic"
        {% if not project.picture %}
          src="{{url_for('static', filename='img/wisdom.jpg')}}"
        {% else %}
          src="{{ project.picture }}"
        {% endif %}
        />
      </div>
      <div class="col project-text">
        {{ ('\n'.join(project.body.split('\n')[:2]))|markdown }}
      </div>
    </div>
    <div class="row">
      <div class="col text-right">
        <a href="{{ url_for('.project', pid=project.id) }}">Read more >></a>
      </div>
    </div>
  </div>
  <hr class="project-divider" />
  {% endfor %} 
  
</div>

{% endblock %}

app/templates/success.html
{% extends "base.html" %}

{% block title %} Flask - success {% endblock %}

{% block content %}
{{ super() }}
<div class="text-center">
    <table width="50%" style="margin-left: auto; margin-right: auto; margin-top: 10px;">
        <tr>
            <td>
                <h1>Congratulations!</h1>
                <h2>Welcome to the machine!</h2>
            </td>
        </tr>
        <tr>
            <td>
                <img src="/static/img/thumbs-up.png" width=30% id="okpic">
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    You have successfully created your account. To finish your registration, please confirm your email
                    by clicking the link in the letter, that has just been sent to you. If it's not in your inbox, please
                    check spam. Google filters can be unpredictable sometimes. <br>
                    I promise you, the link is totally safe. Fear not, {{ user.name }}.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    But you can already login and enjoy your newly gained access!
                </p>
            </td>
        </tr>
    </table>
</div>
{% endblock %}